services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: ahmad
      POSTGRES_PASSWORD: rahasia
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  my_network:
    driver: bridge
