server:
    port: 8081
spring:
    datasource:
        url: jdbc:postgresql://0.0.0.0:5432/ecommerce
        driver-class-name: org.postgresql.Driver
        username: ahmad
        password: rahasia
        hikari:
            connection-timeout: 20000
            maximum-pool-size: 5
        ports:
            - "5432:5432"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    expirationMs: 3600000
    secret: yC2rMJfQHRMiAOUf5ZsR2YZ+sn3Y2JRhUtHkyoWhK0Km0YrD6XVaROkIoE8rRUSppdODssm3GPYMQYrjOBDJyQ==
    refreshExpirationMs : 360000000
